### PR TITLE
Use BigInt instead of bn.js

### PR DESCRIPTION
**Pull request by lPernod-sorare**
`@noble/*` and `@scure/*` libs were audited by scure in Jan 2022
https://github.com/paulmillr/noble-hashes#security
https://github.com/paulmillr/noble-curves#security
https://github.com/paulmillr/scure-bip32#security
https://github.com/paulmillr/scure-bip39#security
https://github.com/paulmillr/scure-base#security

### CODE REVIEW

**Review by utay — APPROVED** [review]
:fire:

**Comment by redox** [comment]
So no C++ needed anymore?

**Comment by lPernod-sorare** [comment]
> So no C++ needed anymore?

Yes correct, the C++ was also removed as part of this MR. The bindings depended on `bn.js` which this MR aims to deprecate.

The current implementation is slightly slower than the C++ implementation, but much closer in performance to the C++ implementation than the previous JS implementation:

Master (JS) ~ 2000ms
Master (C++) ~ 2ms
This MR (JS) ~ 6ms

**Review by piedup — APPROVED** [review]
🔥

**Pull request merged**
